# Generated by Django 3.0.5 on 2020-07-08 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2020, 1, 1))),
                ('time', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
